sudo: required
services:
  - docker

before_install:
  - docker build -t zm/react-test -f ./client/Dockerfile.dev ./client

# tutaj wszystkie komendy niezbędne do wykonania testów. Travis będzie sprawdzał rezultat każdej z tych komend
# Jako ostatnie parameter docker run jest polecenie, które będzie wykonane w kontenerze po uruchomieniu jego
# w tym przypadku jest to npm run test .  -- --coverage to komenda, która 
script:
  - docker run zm/react-test npm test -- --coverage

# teraz budowane sa produkcyjne kontenery, wykorzystują defaultowe nazwy Dockerfile
after_success:
  - docker build -t zbyszekm/multi-container-client ./client
  - docker build -t zbyszekm/multi-container-nginx ./nginx
  - docker build -t zbyszekm/multi-container-server ./server
  - docker build -t zbyszekm/multi-container-worker ./worker


# Log in to the Docker. Credentials travis weźmie z environment variables skonfigurowanych w travis-ci.org
# dziwnie to wygląda, nie rozumiem, dlaczego nie można by było umieścić hasła tak samo jak id
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

# push to docker hub

  - docker push zbyszekm/multi-container-client
  - docker push zbyszekm/multi-container-nginx 
  - docker push zbyszekm/multi-container-server
  - docker push zbyszekm/multi-container-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-central-1"
  app: "ZM-MultiContainer" # nazwa aplikacji zgodnie z tym co jest w Elastic Beanstalk (EBS)
  env: "ZmMultiContainer-env" # nazwa pierwszego środowiska w EBS
  bucket_name: "elasticbeanstalk-eu-central-1-392634375159" #nazwa bucketu, do którego uploadowany jest kod. JEDEN bucket dla wszystkich projektów EBS
  bucket_path: "multi-container"
  skip_cleanup: true # dodałem za dokumentacją travis by uniknąć problemu "no stash entries found" podczas deployowania do EBS
  on:
    branch: master # trigger deployment TYLKO jeśli zostanie skomitowana zmiana w master branch kodu
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY" # nie wiadomo dlaczego tutaj zadziałało autorowi tylko jeśli w ""